name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install ffmpeg libsm6 libxext6 -y
      - name: Train model for trash classification
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python dataset_collection.py
          python train.py
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Display results
          echo "## Model Training Report" > report.md
          
          echo "### Performance Metrics" >> report.md
          cat metrics.txt >> report.md
          cml-send-comment report.md